export const listAsset = [
  {
    code: "XLM",
    issuer: "GAZDAUCRI3E7APVYGOPLLS6CMMCCXTUZ6ZKWPOS2EMOOGIGOIQWHWYTQ",
  },
  {
    code: "LSP",
    issuer: "GAZDAUCRI3E7APVYGOPLLS6CMMCCXTUZ6ZKWPOS2EMOOGIGOIQWHWYTQ",
  },
  {
    code: "AQUA",
    issuer: "GAZDAUCRI3E7APVYGOPLLS6CMMCCXTUZ6ZKWPOS2EMOOGIGOIQWHWYTQ",
  },
  {
    code: "TERN",
    issuer: "GAZDAUCRI3E7APVYGOPLLS6CMMCCXTUZ6ZKWPOS2EMOOGIGOIQWHWYTQ",
  },
  {
    code: "USDC",
    issuer: "GAZDAUCRI3E7APVYGOPLLS6CMMCCXTUZ6ZKWPOS2EMOOGIGOIQWHWYTQ",
  },
  {
    code: "YBX",
    issuer: "GAZDAUCRI3E7APVYGOPLLS6CMMCCXTUZ6ZKWPOS2EMOOGIGOIQWHWYTQ",
  },
];
